[build]
  command = "yarn run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "8.11.4"

[[redirects]]
  from = "/client-form"
  to = "https://s2clraio2ws.typeform.com/to/M1ZkR7AX"
  status = 302
